"""initial_schema

Revision ID: 6fdf3c98af9c
Revises: 
Create Date: 2026-04-14 17:04:15.658067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdf3c98af9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('row_hmac', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('retention_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_or_profile', sa.String(length=128), nullable=False),
    sa.Column('noncritical_days', sa.Integer(), nullable=False),
    sa.Column('critical_days', sa.Integer(), nullable=False),
    sa.Column('keep_original_days', sa.Integer(), nullable=True),
    sa.Column('auto_delete_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_or_profile')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('admin', 'reviewer', 'viewer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_path', sa.String(length=512), nullable=False),
    sa.Column('working_copy_path', sa.String(length=512), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('fps_nominal', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=128), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('ingested_by', sa.String(length=128), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'hashing', 'quarantine', 'scanning', 'processing', 'completed', 'failed', name='video_status'), nullable=False),
    sa.Column('error_code', sa.String(length=16), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_sha256'), ['sha256'], unique=False)
        batch_op.create_index('ix_videos_status', ['status'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('event_index', sa.Integer(), nullable=False),
    sa.Column('start_pts_ms', sa.Integer(), nullable=False),
    sa.Column('end_pts_ms', sa.Integer(), nullable=False),
    sa.Column('start_frame', sa.Integer(), nullable=False),
    sa.Column('end_frame', sa.Integer(), nullable=False),
    sa.Column('peak_motion_score', sa.Float(), nullable=False),
    sa.Column('peak_frame', sa.Integer(), nullable=False),
    sa.Column('total_motion_area', sa.Float(), nullable=False),
    sa.Column('detection_mode', sa.Enum('motion_only', 'motion_detector', 'motion_detector_tracker', name='detection_mode'), nullable=False),
    sa.Column('event_status', sa.Enum('pending_review', 'reviewed', 'dismissed', name='event_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'event_index', name='uq_event_video_index')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_video_id', ['video_id'], unique=False)

    op.create_table('video_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('codec', sa.String(length=32), nullable=True),
    sa.Column('bit_rate', sa.Integer(), nullable=True),
    sa.Column('creation_time', sa.String(length=64), nullable=True),
    sa.Column('container_format', sa.String(length=32), nullable=True),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('frame_ref', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('bbox_x2', sa.Float(), nullable=False),
    sa.Column('bbox_y2', sa.Float(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=True),
    sa.Column('backend_used', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.Enum('thumbnail_webp', 'clip_mp4', 'mask_png', name='asset_type'), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=128), nullable=True),
    sa.Column('label_manual', sa.Enum('person', 'vehicle_car', 'vehicle_moto', 'animal', 'shadow', 'bird', 'false_alarm', 'other', name='review_label'), nullable=True),
    sa.Column('is_false_alarm', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='priority_level'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_event_id', ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_event_id')

    op.drop_table('reviews')
    op.drop_table('event_assets')
    op.drop_table('detections')
    op.drop_table('video_metadata')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_video_id')

    op.drop_table('events')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index('ix_videos_status')
        batch_op.drop_index(batch_op.f('ix_videos_sha256'))

    op.drop_table('videos')
    op.drop_table('users')
    op.drop_table('retention_policies')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
